//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPay.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PcPay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://dev3.mitec.com.mx.
        /// </summary>
        internal static string DevTempURL {
            get {
                return ResourceManager.GetString("DevTempURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string j {
            get {
                return ResourceManager.GetString("j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para asuntos relacionados con el sistema, favor de llamar a:|D.F. y Área metropolitana: (55) 51-69-43-27|Del interior de la república: 01 800 999 01 10|Correo: comercios-santander-elavon@mitec.com.mx.
        /// </summary>
        internal static string MSSGMASIVOS {
            get {
                return ResourceManager.GetString("MSSGMASIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para asuntos relacionados con el sistema, favor de llamar a:|D.F. y Área metropolitana: (55) 15-00-90-00|Correo: soporte@mitec.com.mx.
        /// </summary>
        internal static string MSSGMIT {
            get {
                return ResourceManager.GetString("MSSGMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para asuntos relacionados con el sistema, favor de llamar a:|D.F. y Área metropolitana: (55) 51-69-43-27|Del interior de la república: 01 800 999 01 10|Correo: comercios-santander-elavon@mitec.com.mx .
        /// </summary>
        internal static string MSSGTRAVEL {
            get {
                return ResourceManager.GetString("MSSGTRAVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;PNPRESPONSE&gt;
        ///	&lt;cd_status&gt;1&lt;/cd_status&gt;
        ///	&lt;nb_status&gt;success&lt;/nb_status&gt;
        ///	&lt;cd_error/&gt;
        ///	&lt;nb_error/&gt;
        ///	&lt;datos count=&quot;2&quot;&gt;
        ///		&lt;coupon&gt;&lt;code&gt;1CHCRNQ1ADA2UE4B&lt;/code&gt;&lt;desc&gt;Cupon 1 multiusos uno B644|Obten 10.00% de descuento&lt;/desc&gt;&lt;vigencia&gt;Del 17/11/2015 al 01/12/2015&lt;/vigencia&gt;
        ///		&lt;/coupon&gt;
        ///		&lt;coupon&gt;&lt;code&gt;NJH7L2L8CNUXXJVP&lt;/code&gt;&lt;desc&gt;Cupon 2 uso uno B644|Un regalo sorpresa de obsequio&lt;/desc&gt;&lt;vigencia&gt;Del 18/11/2015 al 02/12/2015&lt;/vigencia&gt;
        ///		&lt;/coupon&gt;
        ///		&lt;coupon&gt;&lt;code&gt;aa1&lt;/code&gt;&lt;desc&gt;Cupon 3 uso uno B644|U [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string MULTICUPONES {
            get {
                return ResourceManager.GetString("MULTICUPONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pgs/jsp/cpagos/cargas/Picture/pcpayNV.
        /// </summary>
        internal static string remoteImg {
            get {
                return ResourceManager.GetString("remoteImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10.0.0.
        /// </summary>
        internal static string VersionPcPay {
            get {
                return ResourceManager.GetString("VersionPcPay", resourceCulture);
            }
        }
    }
}
